### ISSUE TITLE
Docs: Change the names of The Hidden Lake services to an understandable ones

### ISSUE THREAD

**Issue by hizani** [number571/go-peer#16]
HLS, HLM, HLT etc. are very obscure names with the same "HL" prefix that can be omitted. I think it is better to just use "Service", "Manager" or whatever name fits the particular service to make the Readme file more understandable

**Comment by hizani** [comment]
I just noticed that the deciphering of the service names and their roles are described in the main readme file. I think it would be better to link the service names in the HL Readme with the corresponding headers in the main go-peer Readme.

**Comment by number571** [comment]
Thank you for your interest in the project. The HL prefix was made to indicate that the service belongs to the applications of the Hidden Lake network. If they were just referred to as "Messenger", "Filesharer", etc., they would be faceless. On the other hand, I didn't want to name them individually either, in isolation from the Hidden Lake project. Thus, the best solution was to introduce a prefix that gives both individuality (in comparison with the list of other messengers, file sharing applications, etc.) and belonging to a common code base.
As for transferring the description of Hidden Lake services from Readme go-peer to Readme HL - here I agree, logically it will be more correct. I will try to do this in the future.

**Comment by number571** [comment]
Removed from the root README.md description of Hidden Lake network services. Changed the "Library based applications" section, moved the list of HL applications to cmd/hidden_lake/README.md. It has become less loaded and more minimalistic. Thanks for the helpful comment.
