### ISSUE TITLE
Consider using well-known pbkdf in `crypto/entropy`

### ISSUE THREAD

**Issue by cpud36** [number571/go-peer#4]
From the source:
```go
// Increase entropy by multiple hashing.
func (p *sEntropyBooster) BoostEntropy(pData []byte) []byte {
```

The comment is misleading. This function does not and cannot increase entropy.

IIUC, this function is a password-based key derivation. That is it derives key-material from a _password_ and the salt. 

It is important to only feed passwords as a key. Feeding a proper key material to this function might _reduce_ security. So it might be beneficial to rename the parameter to `password`.

And last but not least, instead of using a variation PBKDF1, it might be better to use a modern algorithm, like argon, scrypt, or at least bcrypt. What is your position on this?

**Comment by number571** [comment]
> The comment is misleading. This function does not and cannot increase entropy.

It can increase. When designing the entropy booster, I was guided by Chapter 22 (Secret Storage), section 2.1 (Salt and Stretch) from the book "Practical Cryptography" (N. Ferguson, B. Schneier):

> What kind of winnings did we get? If r = 2^20 (this is a little more than a million), then the attacker will have to perform 2^20 hashing operations to verify each password option. Iterating over 2^60 passwords requires 2^80 hashing operations, so using r = 220 is equivalent to increasing the password size by 20 bits. The greater the value of r, the greater the gain in the size of the password we get.

> Feeding a proper key material to this function might reduce security.

I don't quite understand what exactly can reduce security when transferring a non-password? If we consider a certain randomness with an entropy equal to N, then IEntropyBooster will increase this parameter by +X (of course, taking into account that N will not exceed the size of the hash function itself).

> And last but not least, instead of using a variation PBKDF1, it might be better to use a modern algorithm, like argon, scrypt, or at least bcrypt. What is your position on this?

Indeed, it would be possible to use one of these algorithms. The reason why I didn't do it was: 
1. simplicity of implementation, where the vulnerability can be hidden in only 10 lines of code; 
2. Scrypt similarity algorithms make calculations more complex when using FPGAs and their like, equating them to more or less one computing resource. But at the same time, scrypt does not change in any way and does not make the algorithmic complexity of the search itself less. 

However, there really are a number of problems in my choice that the same scrypt can solve. For example, the size of the resulting block. Now it is equal to the SHA256 block size. Also, protection from FPGA will be quite a plus. Therefore, I think I will really rewrite the crypto/entropy implementation soon.

**Comment by cpud36** [comment]
> It can increase. When designing the entropy booster, I was guided by Chapter 22 (Secret Storage), section 2.1 (Salt and Stretch) from the book "Practical Cryptography" (N. Ferguson, B. Schneier):

The entropy is a measure of true randomness, not computational complexity. Entropy can be coarsely defined as "what is the expected number of tries one needs to guess the password" (specifially a log2 of it).

So a non-random function `H(k)` cannot increase entropy. Moreover, if `H(k)` is not injective (has collisions), it will reduce the entropy (we have fewer choices). I assume that `salt` is public and cannot be accounted as a source of randomness.

> I don't quite understand what exactly can reduce security when transferring a non-password?

Password-based kdf are desinged to be fed with low-entropy keys. Due to collisions pb-kdf might reduce entropy. This is not a concern for passwords as the possibility is neglible.

High-entropy key material has pretty high possibility of hitting collisions, and thus pb-kdf will substantially reduce entropy of KM.

> 2. Scrypt similarity algorithms make calculations more complex when using FPGAs and their like, equating them to more or less one computing resource. But at the same time, scrypt does not change in any way and does not make the algorithmic complexity of the search itself less.

Neither pbkdf change algorithmic complexity. Pbkdfs are specifically designed as a band-aid to slow down bruteforce attack. Algorithmically all pbkdfs have constant complexity (assuming fixed output size and cost hyperparam). They only differ in performance by a constant factor.

>.... The reason why I didn't do it was:
>1. simplicity of implementation, where the vulnerability can be hidden in only 10 lines of code;

If implementation simplicity is a concern, then you can use pbkdf2. It is similar to your impl, but uses a proper HMAC and has well-studied security.

And to state the common truth: do not roll your own crypto.

**Comment by number571** [comment]
Translated the implementation to pbkdf2. Also changed the naming. The amendments are in the commit: https://github.com/number571/go-peer/commit/533c45d99e5dc829c4d13d815360614c505c428d. Thanks for pointing out the problem
