### ISSUE TITLE
README: Simple typo

### ISSUE THREAD

**Issue by Antonboom** [number571/go-peer#7]
> 5. The network/anonymity module to ensure anonymity based on the fifth^ stage. Presents the main functions for working with the network on top of the network and queue modules.

expected

> based on the **fourth**^ stage

?

**Comment by number571** [comment]
Thank you for your interest in the project, the fifth^ stage is the right option. This stage is characterized by the possibility of creating anonymous communications without polymorphism (variability) of information. The first^ and fifth^ stages (compared to the classical ones) arise as a result of the transition of decentralized systems from the state of a communication platform to a routing platform.

More information about this (in Russian language):
- [Theory of the structure of hidden systems](https://github.com/number571/go-peer/blob/master/docs/theory_of_the_structure_of_hidden_systems.pdf),
- [Grok anonymity](https://github.com/number571/go-peer/blob/master/docs/grok_anonymity.pdf).

**Comment by Antonboom** [comment]
Sorry 👍 
Thank you for cool work
